# Generated by Django 4.0.8 on 2022-12-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Succeed', 'Succeed'), ('Failed', 'Failed'), ('Canceled', 'Canceled')]),
        ),
    ]
