# Generated by Django 4.0.8 on 2022-12-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mailing_started_at_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mobile_operator_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
