# Generated by Django 4.0.8 on 2022-12-18 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number is invalid! It should follow the pattern '7XXXXXXXXXX' where X is a digit between 0 and 9", regex='^7[0-9]{10}$')]),
        ),
    ]
